@url=http://localhost:3000

### Obtener todos los viajes
GET {{url}}/viajes

### Obtener todos los viajes de un conductor o vehiculo
GET {{url}}/viajes?conductor=9&vehiculo=3

### Crear un nuevo viaje 
POST {{url}}/viajes
Content-Type: application/json

{
    "vehiculo_id": 3, 
    "conductor_id": 9,
    "fecha_salida": "2025-11-13", 
    "fecha_llegada": "2025-11-14", 
    "origen": "La Rioja", 
    "destino": "Tucuman", 
    "kilometros": 400, 
    "observaciones": "Se pincho una llanta"
}

### Actualizar datos de un viaje 
PUT {{url}}/viajes/1
Content-Type: application/json

{
    "vehiculo_id": 3, 
    "conductor_id": 9,
    "fecha_salida": "2025-11-13", 
    "fecha_llegada": "2025-11-14", 
    "origen": "La Rioja", 
    "destino": "Cordoba", 
    "kilometros": 500, 
    "observaciones": "Sin observaciones"
}

### Eliminar un viaje
DELETE {{url}}/viajes/2